services:
  # FastAPI Application (Development)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: expense_tracker_app_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      ALGORITHM: ${ALGORITHM:-HS256}
    volumes:
      - .:/app:ro  # Read-only mount for development
      - /app/.venv  # Anonymous volume for virtual environment
    ports:
      - "8000:8000"
    networks:
      - expense_tracker_network
    profiles:
      - dev
    security_opt:
      - no-new-privileges:true

  # FastAPI Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: expense_tracker_app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      ALGORITHM: ${ALGORITHM:-HS256}
    ports:
      - "8000:8000"
    networks:
      - expense_tracker_network
    profiles:
      - prod
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Nginx Reverse Proxy (Production only)
  nginx:
    image: nginx:alpine
    container_name: expense_tracker_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - app
    networks:
      - expense_tracker_network
    profiles:
      - prod
    security_opt:
      - no-new-privileges:true

  # Database migrations service
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: expense_tracker_migrate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["uv", "run", "alembic", "upgrade", "head"]
    networks:
      - expense_tracker_network
    profiles:
      - migrate
    security_opt:
      - no-new-privileges:true

networks:
  expense_tracker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16