services:
  - type: web
    name: expense-tracker-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ALGORITHM
        value: "HS256"
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    user: expense_tracker_user
