"""Add bank_balance and cash_balance to users

Revision ID: 1e540fa3ccb8
Revises: 
Create Date: 2025-09-17 10:20:02.702665

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e540fa3ccb8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('users', sa.Column('bank_balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('cash_balance', sa.Integer(), nullable=True))
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'cash_balance')
    op.drop_column('users', 'bank_balance')
    op.alter_column('expenses', 'amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
