name: CI

on:
  push:
    branches: [ main, render-deployment ]
  pull_request:
    branches: [ main, render-deployment ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run tests
      run: uv run pytest
      env:
        TEST_ENV: true
        SECRET_KEY: test-secret-key
        DATABASE_URL: sqlite:///test.db
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        ALGORITHM: HS256
        CORS_ORIGINS: "*"
